source 'https://github.com/CocoaPods/Specs.git'
target 'ting' do
    pod 'GoogleMaps'
    pod 'GooglePlaces'
    pod 'GoogleSignIn'
    pod 'Floaty'
    pod 'FittedSheets'
    pod 'Kingfisher'
    use_frameworks!
    pod 'ReachabilitySwift', '= 4.3.0'
    pod 'ImageViewer', :git => 'https://github.com/Krisiacik/ImageViewer.git'
    pod 'Charts'
    pod 'XLPagerTabStrip'
    pod 'GradientLoadingBar'
    pod 'FaveButton'
    pod 'Windless'
    pod 'LoadingShimmer'
    pod 'ShimmerSwift'
    pod 'ViewPager-Swift'
    pod 'BEMCheckBox'
    pod 'SimpleCheckbox'
    pod 'ScalingCarousel'
    pod 'ToosieSlide', '~> 1.1'
    pod 'MercariQRScanner'
    pod 'CircularRevealKit'
    pod 'PubNubSwift'
    pod 'PushNotifications'
    pod 'PusherSwift', '= 7.2.0'
    pod 'SwiftDataTables'
    pod 'BulletinBoard'
    pod 'CameraKit-iOS'
    pod 'YPImagePicker'
    pod 'YNSearch'
    pod 'SwiftToast'
    pod 'Atributika'
end
