source 'https://github.com/CocoaPods/Specs.git'
target 'ting' do
    pod 'GoogleMaps'
    pod 'GooglePlaces'
    pod 'GoogleSignIn'
    pod 'Floaty'
    pod 'FittedSheets'
    pod 'Kingfisher'
    use_frameworks!
    pod 'ReachabilitySwift'
    pod 'ImageViewer', :git => 'https://github.com/Krisiacik/ImageViewer.git'
    pod 'Charts'
    pod 'XLPagerTabStrip'
    pod 'GradientLoadingBar'
    pod 'FaveButton'
    pod 'Windless'
    pod 'LoadingShimmer'
    pod 'ShimmerSwift'
    pod 'ViewPager-Swift'
    pod 'BEMCheckBox'
    pod 'SimpleCheckbox'
    pod 'ScalingCarousel'
    pod 'ToosieSlide', '~> 1.1'
    pod 'MercariQRScanner'
end
